spring.application.name=CloudNest
server.servlet.context-path = /api/v1.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration 

spring.mongodb.uri=mongodb+srv://${DB_USER}:${DB_PASSWORD}@cloudnest-db.prjazpu.mongodb.net/cloudnest?authSource=admin&appName=CloudNest-DB
spring.data.mongodb.auto-index-creation=true


# Clerk Details
clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret = ${CLERK_WEBHOOK_SECRET}

#File Upload Config
spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 25MB

file.upload-dir=./uploads

